// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemplaTask.DAL;

#nullable disable

namespace TemplaTask.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230528153600_AddFooterAndSocialNetworksAndDownloadsTables")]
    partial class AddFooterAndSocialNetworksAndDownloadsTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TemplaTask.DAL.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FooterId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FooterId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("TemplaTask.DAL.Entities.Downloads", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("FooterId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FooterId");

                    b.ToTable("Downloads");
                });

            modelBuilder.Entity("TemplaTask.DAL.Entities.Footer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Designer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Footer");
                });

            modelBuilder.Entity("TemplaTask.DAL.Entities.SocialNetworks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("FooterId")
                        .HasColumnType("int");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FooterId");

                    b.ToTable("SocialNetworks");
                });

            modelBuilder.Entity("TemplaTask.DAL.Entities.Contact", b =>
                {
                    b.HasOne("TemplaTask.DAL.Entities.Footer", null)
                        .WithMany("Contacts")
                        .HasForeignKey("FooterId");
                });

            modelBuilder.Entity("TemplaTask.DAL.Entities.Downloads", b =>
                {
                    b.HasOne("TemplaTask.DAL.Entities.Footer", null)
                        .WithMany("Downloads")
                        .HasForeignKey("FooterId");
                });

            modelBuilder.Entity("TemplaTask.DAL.Entities.SocialNetworks", b =>
                {
                    b.HasOne("TemplaTask.DAL.Entities.Footer", null)
                        .WithMany("SocialNetworks")
                        .HasForeignKey("FooterId");
                });

            modelBuilder.Entity("TemplaTask.DAL.Entities.Footer", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Downloads");

                    b.Navigation("SocialNetworks");
                });
#pragma warning restore 612, 618
        }
    }
}
